import type { JobInsight } from "@/types";

/**
 * 岗位透视种子数据。阶段四接入 DeepSeek 后，API 将优先调用 AI 生成并回退到此数据。
 */
export const JOB_INSIGHTS: Record<string, JobInsight> = {
  AI产品经理: {
    title: "AI产品经理",
    salaryRange: "25k - 45k / 月（一线互联网，0-3年）",
    education: "本科及以上，计算机 / 信息管理 / 统计学优先",
    hardSkills: [
      "Prompt 设计与 LLM 应用落地",
      "数据分析与 A/B 测试",
      "Axure / Figma 原型设计",
      "Python 或 SQL 基础",
      "AI 产品合规与伦理意识",
    ],
    intensity: "高",
    intensityScore: 8,
    careerPath: [
      "AI 产品助理 → AI 产品经理 → 高级 AI PM / AI 产品负责人",
      "可转向 AI 解决方案架构师或创业方向",
    ],
    summary:
      "负责将大模型能力转化为可规模化的产品功能，需要在技术可行性、用户体验与商业目标之间做平衡。当前赛道需求旺盛，但竞争同样激烈，具备「产品 + AI 理解 + 数据驱动」复合能力者更占优势。",
    updatedAt: "2026-07-25",
  },
  数据产品经理: {
    title: "数据产品经理",
    salaryRange: "20k - 38k / 月（一线，0-3年）",
    education: "本科及以上，数学 / 统计 / 计算机相关优先",
    hardSkills: ["SQL", "数据指标体系设计", "BI 工具", "用户行为分析", "跨团队沟通"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["数据产品助理 → 数据 PM → 数据产品负责人 / 增长负责人"],
    summary:
      "聚焦数据资产的产品化与指标体系建设，是连接业务与数据团队的关键角色，对逻辑与结构化思维要求较高。",
    updatedAt: "2026-07-25",
  },
  增长产品经理: {
    title: "增长产品经理",
    salaryRange: "22k - 40k / 月（一线，0-3年）",
    education: "本科及以上，不限专业但需强数据意识",
    hardSkills: ["增长黑客方法论", "漏斗分析", "实验设计", "用户分层运营", "产品迭代"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["增长产品 → 高级增长 PM → 增长负责人 / CMO 路径"],
    summary:
      "以拉新、激活、留存、转化为核心 KPI，工作节奏快、结果导向强，适合抗压能力强且喜欢实验驱动的同学。",
    updatedAt: "2026-07-25",
  },
  前端工程师: {
    title: "前端工程师",
    salaryRange: "18k - 35k / 月（一线，0-3年）",
    education: "本科及以上，计算机相关专业优先",
    hardSkills: ["JavaScript / TypeScript", "React / Vue", "CSS 工程化", "性能优化", "工程化工具链"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["初级前端 → 高级前端 → 前端架构师 / 全栈"],
    summary: "负责 Web / 移动端界面实现，技术栈更新快，需要持续学习，但岗位基数大、路径清晰。",
    updatedAt: "2026-07-25",
  },
  算法工程师: {
    title: "算法工程师",
    salaryRange: "30k - 55k / 月（一线，应届 - 3年）",
    education: "硕士及以上更常见，计算机 / AI / 数学相关专业",
    hardSkills: ["Python", "机器学习 / 深度学习", "PyTorch / TensorFlow", "论文阅读", "工程落地"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["算法工程师 → 高级算法 → 算法专家 / AI 架构师"],
    summary: "门槛高、竞争激烈，头部公司偏好有论文或竞赛经历的候选人，但薪资天花板也更高。",
    updatedAt: "2026-07-25",
  },
  全栈工程师: {
    title: "全栈工程师",
    salaryRange: "20k - 38k / 月（一线，0-3年）",
    education: "本科及以上，计算机相关专业",
    hardSkills: ["前后端开发", "数据库设计", "API 设计", "DevOps 基础", "系统设计"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["全栈工程师 → 高级全栈 → 技术负责人 / 创业"],
    summary: "适合初创团队或需要端到端交付的场景，技能面广，对自学能力要求高。",
    updatedAt: "2026-07-25",
  },
  出海运营: {
    title: "出海运营",
    salaryRange: "15k - 30k / 月（一线，0-3年）",
    education: "本科及以上，英语 / 小语种能力加分",
    hardSkills: ["海外市场洞察", "Google / Meta 投放", "本地化内容", "数据分析", "跨文化沟通"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["出海运营专员 → 出海运营负责人 → 海外市场负责人"],
    summary:
      "伴随中国企业全球化浪潮需求上升，需同时理解产品、渠道与本地化，加班与跨时区协作较常见。",
    updatedAt: "2026-07-25",
  },
  用户运营: {
    title: "用户运营",
    salaryRange: "12k - 25k / 月（一线，0-3年）",
    education: "本科及以上，专业不限",
    hardSkills: ["用户分层", "活动策划", "社群运营", "数据复盘", "文案能力"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["用户运营 → 高级运营 → 运营负责人 / 增长"],
    summary: "入门门槛相对友好，强调对用户行为的理解与执行力，适合作为互联网运营起点。",
    updatedAt: "2026-07-25",
  },
  内容运营: {
    title: "内容运营",
    salaryRange: "12k - 24k / 月（一线，0-3年）",
    education: "本科及以上，中文 / 新闻 / 传媒优先",
    hardSkills: ["内容策划", "平台算法理解", "短视频脚本", "数据分析", "品牌传播"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["内容运营 → 内容负责人 → 品牌 / 市场方向"],
    summary: "需要持续产出优质内容并跟踪传播效果，对创意与热点敏感度要求较高。",
    updatedAt: "2026-07-25",
  },
  管理咨询顾问: {
    title: "管理咨询顾问",
    salaryRange: "20k - 40k / 月（MBB /  Tier2，应届）",
    education: "985 / 211 或海外名校，本科及以上",
    hardSkills: ["结构化思维", "PPT / Excel", "行业研究", "客户沟通", "英语"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["分析师 → 顾问 → 项目经理 → 合伙人 / 企业战略岗"],
    summary: "高强度、高曝光，训练商业思维与解决问题能力，但出差与加班Culture显著。",
    updatedAt: "2026-07-25",
  },
  商业分析师: {
    title: "商业分析师",
    salaryRange: "15k - 28k / 月（0-3年）",
    education: "本科及以上，商科 / 经济 / 统计优先",
    hardSkills: ["Excel / SQL", "商业建模", "行业分析", "报告撰写", "数据可视化"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["商业分析 → 高级 BA → 战略分析 / 产品经理"],
    summary: "连接业务与数据的桥梁角色，在互联网与金融行业中均有稳定需求。",
    updatedAt: "2026-07-25",
  },
  公务员: {
    title: "公务员",
    salaryRange: "6k - 12k / 月（因地而异，含福利）",
    education: "本科及以上（部分岗位限应届 / 党员）",
    hardSkills: ["公文写作", "政策理解", "行政协调", "公考能力", "稳定性"],
    intensity: "低",
    intensityScore: 3,
    careerPath: ["科员 → 副科 → 正科 → 更高行政级别"],
    summary: "稳定性强、福利保障完善，但薪资增长相对平缓，需提前规划备考与岗位选择。",
    updatedAt: "2026-07-25",
  },
  事业单位职员: {
    title: "事业单位职员",
    salaryRange: "7k - 14k / 月（因地区与单位差异大）",
    education: "本科及以上，部分岗位需专业对口",
    hardSkills: ["专业知识", "公文处理", "公共服务意识", "考试能力"],
    intensity: "低",
    intensityScore: 3,
    careerPath: ["职员 → 骨干 → 管理岗 / 专业技术岗晋升"],
    summary: "工作节奏相对稳定，适合追求工作生活平衡的同学，但入口竞争逐年加剧。",
    updatedAt: "2026-07-25",
  },
  高校研究员: {
    title: "高校研究员",
    salaryRange: "8k - 18k / 月（含项目与绩效，差异大）",
    education: "博士更常见，部分硕士可进入科研助理岗",
    hardSkills: ["学术研究", "论文写作", "实验设计", "基金申请", "学术汇报"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["科研助理 → 博士后 → 助理教授 / 研究员"],
    summary: "学术路径长、产出周期长，但自由度较高，适合对某一领域有长期研究兴趣的同学。",
    updatedAt: "2026-07-25",
  },
  实验室助理: {
    title: "实验室助理",
    salaryRange: "6k - 12k / 月",
    education: "本科及以上，理工科背景",
    hardSkills: ["实验操作", "数据记录", "文献检索", "仪器维护", "团队协作"],
    intensity: "低",
    intensityScore: 4,
    careerPath: ["实验助理 → 科研助理 → 读研深造 / 研究员"],
    summary: "常作为进入科研体系的起点，适合计划继续深造的同学积累实验室经验。",
    updatedAt: "2026-07-25",
  },
  国企管培生: {
    title: "国企管培生",
    salaryRange: "10k - 18k / 月（一线国企，含福利）",
    education: "本科及以上，985 / 211 优先",
    hardSkills: ["综合素养", "公文写作", "项目管理", "沟通协调", "行业认知"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["管培生 → 部门骨干 → 中层管理"],
    summary: "培养周期长、稳定性强，适合看重组织保障与长期发展的同学。",
    updatedAt: "2026-07-25",
  },
  国企技术岗: {
    title: "国企技术岗",
    salaryRange: "12k - 22k / 月（含福利，因行业差异大）",
    education: "本科及以上，工科背景",
    hardSkills: ["专业技术", "安全生产规范", "项目交付", "文档管理"],
    intensity: "低",
    intensityScore: 4,
    careerPath: ["技术员 → 工程师 → 高级工程师 / 技术管理"],
    summary: "工作节奏相对可控，技术更新速度较互联网慢，但稳定性与福利通常更好。",
    updatedAt: "2026-07-25",
  },
};

/**
 * 按岗位名称获取透视数据；未知岗位则基于标题生成通用模板。
 */
export function getJobInsightByTitle(title: string): JobInsight {
  const existing = JOB_INSIGHTS[title];

  if (existing) {
    return existing;
  }

  return {
    title,
    salaryRange: "待 AI 联网查询（阶段四接入 DeepSeek 后实时更新）",
    education: "本科及以上（具体以目标公司 JD 为准）",
    hardSkills: ["行业知识", "沟通协作", "学习能力", "问题解决"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["初级岗位 → 中级岗位 → 高级 / 管理方向"],
    summary: `${title} 的详细透视数据将在后续版本通过 AI 实时生成，当前为占位模板。`,
    updatedAt: new Date().toISOString().slice(0, 10),
  };
}
