import type { JobInsight } from "@/types";

const UPDATED_AT = "2026-07-27";

function insight(
  title: string,
  data: Omit<JobInsight, "title" | "updatedAt">,
): JobInsight {
  return { title, updatedAt: UPDATED_AT, ...data };
}

/**
 * 岗位透视种子数据。阶段四接入 DeepSeek 后，API 将优先调用 AI 生成并回退到此数据。
 */
export const JOB_INSIGHTS: Record<string, JobInsight> = {
  // —— 互联网 / 科技大厂 ——
  AI产品经理: insight("AI产品经理", {
    salaryRange: "25k - 45k / 月（一线互联网，0-3年）",
    education: "本科及以上，计算机 / 信息管理 / 统计学优先",
    hardSkills: ["Prompt 设计", "LLM 应用落地", "A/B 测试", "原型设计", "AI 合规意识"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["AI 产品助理 → AI 产品经理 → AI 产品负责人"],
    summary:
      "将大模型能力产品化，需在技术可行性、体验与商业目标间平衡。赛道热但竞争激烈，复合型人才更占优势。",
  }),
  数据产品经理: insight("数据产品经理", {
    salaryRange: "20k - 38k / 月（一线，0-3年）",
    education: "本科及以上，数学 / 统计 / 计算机相关优先",
    hardSkills: ["SQL", "指标体系", "BI 工具", "用户行为分析", "跨团队沟通"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["数据产品助理 → 数据 PM → 数据产品负责人"],
    summary: "负责数据资产产品化与指标体系建设，是业务与数据团队的关键桥梁。",
  }),
  策略产品经理: insight("策略产品经理", {
    salaryRange: "22k - 42k / 月（一线，0-3年）",
    education: "本科及以上，商科 / 计算机 / 数学复合背景加分",
    hardSkills: ["商业模式分析", "竞品研究", "Roadmap 规划", "数据分析", "跨部门推动"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["产品助理 → 策略 PM → 产品总监 / 业务负责人"],
    summary: "聚焦平台规则、定价与中长期产品方向，需要强商业判断与结构化思维。",
  }),
  用户运营: insight("用户运营", {
    salaryRange: "12k - 25k / 月（一线，0-3年）",
    education: "本科及以上，专业不限",
    hardSkills: ["用户分层", "活动策划", "社群运营", "数据复盘", "文案能力"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["用户运营 → 高级运营 → 运营负责人 / 增长"],
    summary: "入门门槛相对友好，强调对用户行为的理解与执行力，是互联网运营常见起点。",
  }),
  内容运营: insight("内容运营", {
    salaryRange: "12k - 24k / 月（一线，0-3年）",
    education: "本科及以上，中文 / 新闻 / 传媒优先",
    hardSkills: ["内容策划", "平台算法理解", "短视频脚本", "数据分析", "品牌传播"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["内容运营 → 内容负责人 → 品牌 / 市场方向"],
    summary: "需持续产出优质内容并跟踪传播效果，对创意与热点敏感度要求较高。",
  }),
  增长运营: insight("增长运营", {
    salaryRange: "15k - 28k / 月（一线，0-3年）",
    education: "本科及以上，不限专业但需强数据意识",
    hardSkills: ["漏斗分析", "实验设计", "渠道投放", "用户分层", "增长实验"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["增长运营 → 增长负责人 → 增长 PM / CMO 路径"],
    summary: "以拉新、激活、留存为核心 KPI，节奏快、结果导向强，适合抗压与实验驱动型同学。",
  }),
  出海运营: insight("出海运营", {
    salaryRange: "15k - 30k / 月（一线，0-3年）",
    education: "本科及以上，英语 / 小语种能力加分",
    hardSkills: ["海外市场洞察", "Meta / Google 投放", "本地化内容", "数据分析", "跨文化沟通"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["出海运营专员 → 出海负责人 → 海外市场负责人"],
    summary: "伴随中国企业全球化需求上升，需理解产品、渠道与本地化，跨时区协作较常见。",
  }),
  前端工程师: insight("前端工程师", {
    salaryRange: "18k - 35k / 月（一线，0-3年）",
    education: "本科及以上，计算机相关专业优先",
    hardSkills: ["TypeScript", "React / Vue", "CSS 工程化", "性能优化", "工程化工具链"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["初级前端 → 高级前端 → 前端架构师 / 全栈"],
    summary: "负责 Web / 移动端界面实现，技术栈更新快，岗位基数大、路径清晰。",
  }),
  后端工程师: insight("后端工程师", {
    salaryRange: "20k - 38k / 月（一线，0-3年）",
    education: "本科及以上，计算机相关专业",
    hardSkills: ["Java / Go / Python", "数据库设计", "分布式系统", "API 设计", "性能调优"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["后端工程师 → 高级后端 → 架构师 / 技术负责人"],
    summary: "承担业务逻辑与数据层实现，是大厂核心研发岗，重视代码质量与系统稳定性。",
  }),
  算法工程师: insight("算法工程师", {
    salaryRange: "30k - 55k / 月（一线，应届 - 3年）",
    education: "硕士及以上更常见，计算机 / AI / 数学相关",
    hardSkills: ["Python", "机器学习 / 深度学习", "PyTorch", "论文阅读", "工程落地"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["算法工程师 → 高级算法 → 算法专家 / AI 架构师"],
    summary: "门槛高、竞争激烈，头部公司偏好论文或竞赛经历，但薪资天花板更高。",
  }),
  全栈工程师: insight("全栈工程师", {
    salaryRange: "20k - 38k / 月（一线，0-3年）",
    education: "本科及以上，计算机相关专业",
    hardSkills: ["前后端开发", "数据库设计", "API 设计", "DevOps 基础", "系统设计"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["全栈工程师 → 高级全栈 → 技术负责人 / 创业"],
    summary: "适合初创或需端到端交付的场景，技能面广，对自学能力要求高。",
  }),
  UI设计师: insight("UI设计师", {
    salaryRange: "15k - 28k / 月（一线，0-3年）",
    education: "本科及以上，设计 / 数字媒体相关专业优先",
    hardSkills: ["Figma / Sketch", "设计系统", "视觉规范", "交互协作", "移动端适配"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["UI 设计师 → 高级设计师 → 设计负责人"],
    summary: "负责界面视觉与组件规范，需与产品、研发紧密协作，作品集是核心竞争力。",
  }),
  UX研究员: insight("UX研究员", {
    salaryRange: "16k - 30k / 月（一线，0-3年）",
    education: "本科及以上，心理学 / 人机交互 / 设计相关优先",
    hardSkills: ["用户访谈", "可用性测试", "问卷设计", "体验地图", "研究报告撰写"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["UX 研究员 → 高级研究员 → 体验设计负责人"],
    summary: "通过定性定量研究驱动产品决策，适合逻辑清晰、善于沟通与观察的同学。",
  }),
  数据分析师: insight("数据分析师", {
    salaryRange: "15k - 28k / 月（一线，0-3年）",
    education: "本科及以上，统计 / 数学 / 经济 / 计算机优先",
    hardSkills: ["SQL", "Excel", "Python / R", "可视化", "业务理解"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["数据分析师 → 高级分析师 → 数据 PM / 商业分析负责人"],
    summary: "互联网标配岗位，连接业务与数据，是转向产品、增长、战略的重要跳板。",
  }),
  商业数据分析师: insight("商业数据分析师", {
    salaryRange: "18k - 32k / 月（一线，0-3年）",
    education: "本科及以上，商科 + 数据分析复合背景加分",
    hardSkills: ["商业建模", "SQL", "Tableau / Power BI", "行业研究", "报告撰写"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["商业数据分析 → 战略分析 → 产品 / 投资研究"],
    summary: "侧重经营分析与决策支持，常见于平台型公司与事业部中台团队。",
  }),

  // —— 金融 / 投资机构 ——
  投行分析师: insight("投行分析师", {
    salaryRange: "20k - 45k / 月（头部券商，应届 - 2年）",
    education: "985 / 211 或海外名校，金融 / 会计 / 经济相关",
    hardSkills: ["财务建模", "DCF / 估值", "PPT / Excel", "招股书撰写", "抗压与出差"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["分析师 → Associate → VP → 企业战投 / PE"],
    summary: "高强度、高曝光，训练财务与交易思维，但加班与出差Culture显著，需提前评估耐受度。",
  }),
  并购助理: insight("并购助理", {
    salaryRange: "18k - 38k / 月（券商 / PE，0-3年）",
    education: "本科及以上，金融 / 财务 / 法律复合背景加分",
    hardSkills: ["并购尽调", "交易结构", "财务分析", "行业研究", "英文读写"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["并购助理 → 并购经理 → 投资总监"],
    summary: "参与企业并购与重组项目，对财务、法律与商业理解要求全面，项目制节奏明显。",
  }),
  行业研究员: insight("行业研究员", {
    salaryRange: "15k - 35k / 月（券商 / 基金，0-3年）",
    education: "硕士更常见，经济 / 金融 / 行业相关专业",
    hardSkills: ["行业研究", "财务分析", "报告撰写", "模型搭建", "公开信息挖掘"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["研究员助理 → 行业研究员 → 首席分析师 / 基金经理"],
    summary: "卖方行研是金融校招热门方向，需快速建立行业认知框架与写作输出能力。",
  }),
  基金研究员: insight("基金研究员", {
    salaryRange: "18k - 40k / 月（公募 / 私募，0-3年）",
    education: "硕士及以上更常见，金融 / 数学 / 理工科背景",
    hardSkills: ["个股研究", "估值模型", "行业比较", "路演沟通", "投资笔记"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["研究助理 → 基金经理助理 → 基金经理"],
    summary: "买方研究岗位，直接服务于投资决策，对独立判断与业绩压力要求更高。",
  }),
  量化研究员: insight("量化研究员", {
    salaryRange: "25k - 50k / 月（量化私募 / 券商，0-3年）",
    education: "硕士及以上，数学 / 物理 / 计算机 / 金融工程",
    hardSkills: ["Python / C++", "统计学", "因子挖掘", "回测框架", "论文阅读"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["量化研究员 → 策略负责人 → PM / 创业"],
    summary: "偏理工背景，强调编程与数学建模，头部机构竞争激烈但回报可观。",
  }),
  银行管培生: insight("银行管培生", {
    salaryRange: "10k - 18k / 月（国有 / 股份行，含福利）",
    education: "本科及以上，985 / 211 优先，金融 / 经济 / 会计相关",
    hardSkills: ["金融基础", "客户沟通", "风控意识", "轮岗适应", "公文与合规"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["管培生 → 支行 / 条线骨干 → 中层管理"],
    summary: "轮岗培养路径清晰，稳定性强，适合金融背景同学进入银行体系的正规入口。",
  }),
  对公客户经理: insight("对公客户经理", {
    salaryRange: "12k - 25k / 月（含绩效，因行而异）",
    education: "本科及以上，金融 / 会计 / 市场营销相关",
    hardSkills: ["客户开发", "授信基础", "财务简报阅读", "关系维护", "业绩达成"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["客户经理 → 高级客户经理 → 支行行长 / 条线管理"],
    summary: "面向企业客户的营销与综合服务岗，业绩指标明确，沟通与抗压能力是关键。",
  }),
  风控专员: insight("风控专员", {
    salaryRange: "12k - 22k / 月（银行 / 券商 / 互金，0-3年）",
    education: "本科及以上，金融 / 统计 / 数学 / 计算机相关",
    hardSkills: ["风险模型", "授信政策", "数据分析", "合规流程", "报告撰写"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["风控专员 → 高级风控 → 风控经理 / 合规负责人"],
    summary: "金融机构核心中后台岗位，强调规则意识与细致度，工作节奏相对前台更稳定。",
  }),
  合规专员: insight("合规专员", {
    salaryRange: "12k - 24k / 月（金融机构，0-3年）",
    education: "本科及以上，法律 / 金融 / 会计相关优先",
    hardSkills: ["监管政策", "合规审查", "制度起草", "培训沟通", "风险识别"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["合规专员 → 合规经理 → 首席合规官"],
    summary: "随监管趋严需求稳定，适合法学与金融交叉背景、注重细节的同学。",
  }),
  精算助理: insight("精算助理", {
    salaryRange: "12k - 22k / 月（保险 / 再保险，0-3年）",
    education: "本科及以上，精算 / 数学 / 统计相关专业",
    hardSkills: ["概率统计", "Excel / Python", "精算考试", "产品定价", "准备金评估"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["精算助理 → 精算师 → 首席精算师"],
    summary: "需长期备考精算资格，路径清晰但周期长，适合数学基础扎实的同学。",
  }),
  资管研究员: insight("资管研究员", {
    salaryRange: "15k - 30k / 月（银行资管 / 理财子，0-3年）",
    education: "本科及以上，金融 / 经济 / 会计相关",
    hardSkills: ["固收 / 权益研究", "产品分析", "宏观跟踪", "报告撰写", "监管理解"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["资管研究员 → 投资经理助理 → 投资经理"],
    summary: "银行理财子公司与资管机构常见岗位，连接产品端与投资端。",
  }),

  // —— 专业服务机构 ——
  律师助理: insight("律师助理", {
    salaryRange: "8k - 18k / 月（红圈 / 精品所，0-2年）",
    education: "本科及以上，法学专业，法考进度加分",
    hardSkills: ["法律检索", "合同审查", "尽职调查", "文书起草", "英文合同"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["律师助理 → 律师 → 合伙人 / 法务总监"],
    summary: "律所入门标准路径，工作强度因团队而异，但专业训练系统，适合法学背景同学。",
  }),
  公司法务: insight("公司法务", {
    salaryRange: "12k - 25k / 月（企业法务，0-3年）",
    education: "本科及以上，法学专业，法考优先",
    hardSkills: ["合同管理", "合规咨询", "知识产权", "争议协调", "业务沟通"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["法务专员 → 高级法务 → 法务总监"],
    summary: "嵌入业务一线，工作节奏通常较律所更可控，适合希望进入企业端的法学生。",
  }),
  审计Associate: insight("审计Associate", {
    salaryRange: "10k - 18k / 月（四大，应届 - 2年）",
    education: "本科及以上，会计 / 审计 / 财务管理专业",
    hardSkills: ["会计准则", "底稿编制", "Excel", "客户沟通", "CPA 备考"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["Associate → Senior → Manager → 企业财务 / 投行"],
    summary: "忙季加班显著，但财务基础训练扎实，是会计专业校招最主流入口之一。",
  }),
  税务咨询顾问: insight("税务咨询顾问", {
    salaryRange: "12k - 22k / 月（四大 / 税务所，0-3年）",
    education: "本科及以上，会计 / 税务 / 财务管理 / 法学相关",
    hardSkills: ["税法", "税务筹划", "合规申报", "客户沟通", "CPA / 税务师"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["税务顾问 → 高级顾问 → 税务总监 / 创业"],
    summary: "结合政策解读与企业实践，适合会计与法学交叉、注重细节的同学。",
  }),
  管理咨询顾问: insight("管理咨询顾问", {
    salaryRange: "20k - 40k / 月（MBB / Tier2，应届）",
    education: "985 / 211 或海外名校，本科及以上",
    hardSkills: ["结构化思维", "PPT / Excel", "行业研究", "客户沟通", "英语"],
    intensity: "极高",
    intensityScore: 9,
    careerPath: ["分析师 → 顾问 → 项目经理 → 合伙人 / 企业战略岗"],
    summary: "高强度、高曝光，训练商业思维与解决问题能力，出差与加班Culture显著。",
  }),
  战略咨询分析师: insight("战略咨询分析师", {
    salaryRange: "18k - 35k / 月（咨询 / 战略部门，0-3年）",
    education: "本科及以上，商科 / 经济 / 理工科 Top 校优先",
    hardSkills: ["战略分析", "行业研究", "商业建模", "PPT 叙事", "访谈与调研"],
    intensity: "高",
    intensityScore: 8,
    careerPath: ["战略分析 → 咨询顾问 → 企业战略 / 投资"],
    summary: "聚焦企业中长期方向与竞争策略，输出质量与逻辑深度是核心评价标准。",
  }),
  HR咨询顾问: insight("HR咨询顾问", {
    salaryRange: "12k - 22k / 月（咨询 / 人力公司，0-3年）",
    education: "本科及以上，人力资源 / 心理学 / 工商管理相关",
    hardSkills: ["组织诊断", "薪酬设计", "访谈 facilitation", "报告撰写", "项目管理"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["HR 顾问 → 高级顾问 → 组织发展负责人"],
    summary: "帮助企业优化组织与人才体系，项目制工作，沟通与同理心很重要。",
  }),
  组织发展专员: insight("组织发展专员", {
    salaryRange: "12k - 22k / 月（企业 OD 团队，0-3年）",
    education: "本科及以上，人力资源 / 心理学 / 管理学相关",
    hardSkills: ["组织设计", "人才盘点", "培训项目", "变革沟通", "数据分析"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["OD 专员 → OD 经理 → CHO 路径"],
    summary: "位于企业 HR 高阶职能，参与架构调整与文化建设，适合长期主义型同学。",
  }),

  // —— 实体产业 / 消费品 / 制造业 ——
  供应链管培生: insight("供应链管培生", {
    salaryRange: "10k - 18k / 月（快消 / 制造龙头，含福利）",
    education: "本科及以上，供应链 / 工业工程 / 物流管理相关",
    hardSkills: ["计划协调", "库存管理", "SAP / ERP", "跨部门沟通", "数据分析"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["供应链管培 → 计划 / 采购负责人 → 供应链总监"],
    summary: "制造业与快消核心职能，轮岗机会多，强调流程思维与落地执行。",
  }),
  采购专员: insight("采购专员", {
    salaryRange: "10k - 18k / 月（制造 / 零售，0-3年）",
    education: "本科及以上，供应链 / 材料 / 工商管理相关",
    hardSkills: ["供应商管理", "成本分析", "合同谈判", "质量协调", "ERP 系统"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["采购专员 → 采购经理 → 供应链负责人"],
    summary: "连接生产与市场的重要环节，对成本意识与供应商关系管理要求高。",
  }),
  品牌市场管培生: insight("品牌市场管培生", {
    salaryRange: "10k - 20k / 月（快消 / 消费品牌，0-3年）",
    education: "本科及以上，市场营销 / 广告 / 新闻传播相关",
    hardSkills: ["品牌策略", "Campaign 执行", "消费者洞察", "跨部门协作", "数据分析"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["品牌管培 → 品牌经理 → 市场总监"],
    summary: "快消校招经典路径，轮岗覆盖市场、销售、供应链，适合外向与创意并重的同学。",
  }),
  产品营销专员: insight("产品营销专员", {
    salaryRange: "12k - 22k / 月（消费 / 科技硬件，0-3年）",
    education: "本科及以上，市场营销 / 商科相关专业",
    hardSkills: ["Go-to-market", "竞品分析", "渠道协同", "卖点提炼", "项目推进"],
    intensity: "中",
    intensityScore: 6,
    careerPath: ["产品营销 → 高级 PMM → 市场负责人"],
    summary: "负责产品上市与卖点传播，需同时理解用户、渠道与产品本身。",
  }),
  工艺工程师: insight("工艺工程师", {
    salaryRange: "10k - 18k / 月（制造 / 新能源，0-3年）",
    education: "本科及以上，机械 / 材料 / 化学工程相关",
    hardSkills: ["工艺流程", "良率改善", "CAD", "实验设计", "安全生产"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["工艺工程师 → 高级工程师 → 工厂技术负责人"],
    summary: "实体产业核心岗位，强调现场问题解决与持续改进，路径稳定。",
  }),
  质量工程师: insight("质量工程师", {
    salaryRange: "10k - 18k / 月（制造 / 汽车 / 电子，0-3年）",
    education: "本科及以上，工业工程 / 质量管理 / 理工科背景",
    hardSkills: ["质量体系", "SPC", "8D 分析", "供应商审核", "标准文档"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["质量工程师 → 质量经理 → 质量总监"],
    summary: "保障产品一致性与合规，制造业刚需岗位，细致与责任心是核心素质。",
  }),
  大客户销售: insight("大客户销售", {
    salaryRange: "12k - 30k / 月（含提成，因行业差异大）",
    education: "本科及以上，专业不限但商科 / 工科加分",
    hardSkills: ["客户开发", "方案呈现", "商务谈判", "CRM 管理", "业绩达成"],
    intensity: "高",
    intensityScore: 7,
    careerPath: ["销售代表 → 大客户经理 → 销售总监"],
    summary: "ToB 业务核心岗，收入与业绩挂钩明显，适合目标感强、抗压能力高的同学。",
  }),
  渠道销售: insight("渠道销售", {
    salaryRange: "10k - 22k / 月（含提成，因行业差异大）",
    education: "本科及以上，市场营销 / 工商管理相关",
    hardSkills: ["渠道拓展", "经销商管理", "终端动销", "市场反馈", "区域规划"],
    intensity: "高",
    intensityScore: 6,
    careerPath: ["渠道销售 → 区域经理 → 全国渠道负责人"],
    summary: "覆盖分销与零售终端，需要频繁出差与地推，适合执行力强的同学。",
  }),

  // —— 体制内 / 公共部门 / 国企央企 ——
  公务员: insight("公务员", {
    salaryRange: "6k - 12k / 月（因地而异，含福利）",
    education: "本科及以上（部分岗位限应届 / 党员）",
    hardSkills: ["公文写作", "政策理解", "行政协调", "公考能力", "稳定性"],
    intensity: "低",
    intensityScore: 3,
    careerPath: ["科员 → 副科 → 正科 → 更高行政级别"],
    summary: "稳定性强、福利保障完善，但薪资增长相对平缓，需提前规划备考与岗位选择。",
  }),
  选调生: insight("选调生", {
    salaryRange: "6k - 12k / 月（因地而异，含福利与补贴）",
    education: "本科及以上，限应届，重点院校优先",
    hardSkills: ["公共管理", "基层调研", "公文写作", "政策执行", "群众工作"],
    intensity: "中",
    intensityScore: 4,
    careerPath: ["选调生 → 基层锻炼 → 机关 / 管理岗晋升"],
    summary: "面向优秀应届生的体制内快车道，通常含基层锻炼环节，竞争逐年加剧。",
  }),
  事业单位职员: insight("事业单位职员", {
    salaryRange: "7k - 14k / 月（因地区与单位差异大）",
    education: "本科及以上，部分岗位需专业对口",
    hardSkills: ["专业知识", "公文处理", "公共服务意识", "考试能力"],
    intensity: "低",
    intensityScore: 3,
    careerPath: ["职员 → 骨干 → 管理岗 / 专业技术岗晋升"],
    summary: "工作节奏相对稳定，适合追求工作生活平衡的同学，入口竞争逐年加剧。",
  }),
  高校行政岗: insight("高校行政岗", {
    salaryRange: "7k - 14k / 月（因学校层级差异大）",
    education: "本科及以上，部分岗位要求党员或学生工作经历",
    hardSkills: ["行政协调", "活动组织", "公文写作", "师生沟通", "政策理解"],
    intensity: "低",
    intensityScore: 3,
    careerPath: ["行政科员 → 科室负责人 → 处级管理岗"],
    summary: "高校稳定岗位之一，寒暑假相对完整，适合偏好校园环境的同学。",
  }),
  国企管培生: insight("国企管培生", {
    salaryRange: "10k - 18k / 月（一线国企，含福利）",
    education: "本科及以上，985 / 211 优先",
    hardSkills: ["综合素养", "公文写作", "项目管理", "沟通协调", "行业认知"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["管培生 → 部门骨干 → 中层管理"],
    summary: "培养周期长、稳定性强，适合看重组织保障与长期发展的同学。",
  }),
  国企技术岗: insight("国企技术岗", {
    salaryRange: "12k - 22k / 月（含福利，因行业差异大）",
    education: "本科及以上，工科背景",
    hardSkills: ["专业技术", "安全生产规范", "项目交付", "文档管理"],
    intensity: "低",
    intensityScore: 4,
    careerPath: ["技术员 → 工程师 → 高级工程师 / 技术管理"],
    summary: "工作节奏相对可控，技术更新速度较互联网慢，但稳定性与福利通常更好。",
  }),
  国企财务岗: insight("国企财务岗", {
    salaryRange: "10k - 18k / 月（含福利，因行业差异大）",
    education: "本科及以上，会计 / 财务管理 / 审计相关",
    hardSkills: ["会计核算", "预算管理", "内控合规", "Excel / ERP", "CPA 加分"],
    intensity: "中",
    intensityScore: 4,
    careerPath: ["财务专员 → 财务主管 → 财务总监"],
    summary: "会计专业进入体制内或大型国企的常见路径，强调规范与稳健。",
  }),
  高校研究员: insight("高校研究员", {
    salaryRange: "8k - 18k / 月（含项目与绩效，差异大）",
    education: "博士更常见，部分硕士可进入科研助理岗",
    hardSkills: ["学术研究", "论文写作", "实验设计", "基金申请", "学术汇报"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["科研助理 → 博士后 → 助理教授 / 研究员"],
    summary: "学术路径长、产出周期长，但自由度较高，适合对某一领域有长期研究兴趣的同学。",
  }),
  实验室助理: insight("实验室助理", {
    salaryRange: "6k - 12k / 月",
    education: "本科及以上，理工科背景",
    hardSkills: ["实验操作", "数据记录", "文献检索", "仪器维护", "团队协作"],
    intensity: "低",
    intensityScore: 4,
    careerPath: ["实验助理 → 科研助理 → 读研深造 / 研究员"],
    summary: "常作为进入科研体系的起点，适合计划继续深造的同学积累实验室经验。",
  }),
};

/**
 * 按岗位名称获取透视数据；未知岗位则基于标题生成通用模板。
 */
export function getJobInsightByTitle(title: string): JobInsight {
  const existing = JOB_INSIGHTS[title];

  if (existing) {
    return existing;
  }

  return {
    title,
    salaryRange: "待 AI 联网查询（阶段四接入 DeepSeek 后实时更新）",
    education: "本科及以上（具体以目标公司 JD 为准）",
    hardSkills: ["行业知识", "沟通协作", "学习能力", "问题解决"],
    intensity: "中",
    intensityScore: 5,
    careerPath: ["初级岗位 → 中级岗位 → 高级 / 管理方向"],
    summary: `${title} 的详细透视数据将在后续版本通过 AI 实时生成，当前为占位模板。`,
    updatedAt: new Date().toISOString().slice(0, 10),
  };
}
